apiVersion: v1
kind: Secret
metadata:
  name: myapp-secrets
type: Opaque
data:
  AZURE_SUBSCRIPTION_ID: NDEzNTU5MTMtYTViNC00MDc3LTk2MmItMDg3ZTg2ZjllNDRl
  AZURE_CLIENT_ID: ZjliM2FmNDItNTI0YS00NDA2LWI5ZTEtNTZhNjQ3ZGM0NmRm
  AZURE_CLIENT_SECRET: bzliOFF+Lm5OSkp3RTBJMXhZWjNUVnJsOExIMUtUUno2V3ZGZGNCZw==
  AZURE_TENANT_ID: ZTg2YjcxZmYtNDBmYy00NzY3LThlOGMtNTM4NGNjNWM5MGVh
